export const data = [{
  "id": 1,
  "name": "Layne",
  "city": "Baracatan",
  "code": "TBW"
}, {
  "id": 2,
  "name": "Faith",
  "city": "Tuzha",
  "code": "MZJ"
}, {
  "id": 3,
  "name": "Rebecka",
  "city": "Tabonoc",
  "code": "TFI"
}, {
  "id": 4,
  "name": "Chaunce",
  "city": "Conchagua",
  "code": "GGS"
}, {
  "id": 5,
  "name": "Cobbie",
  "city": "Shuangxi",
  "code": "OER"
}, {
  "id": 6,
  "name": "Mariana",
  "city": "Hongshanyao",
  "code": "NIF"
}, {
  "id": 7,
  "name": "Patrica",
  "city": "Tianguá",
  "code": "BTD"
}, {
  "id": 8,
  "name": "Edgardo",
  "city": "Banatsko Karađorđevo",
  "code": "LNC"
}, {
  "id": 9,
  "name": "Lilyan",
  "city": "Parse",
  "code": "LBM"
}, {
  "id": 10,
  "name": "Dorelia",
  "city": "Qingshuihe",
  "code": "WBU"
}, {
  "id": 11,
  "name": "Martina",
  "city": "Atlanta",
  "code": "HZV"
}, {
  "id": 12,
  "name": "Boycey",
  "city": "Llama",
  "code": "HMJ"
}, {
  "id": 13,
  "name": "Granville",
  "city": "Ridder",
  "code": "MJE"
}, {
  "id": 14,
  "name": "Miof mela",
  "city": "La Sarre",
  "code": "GGC"
}, {
  "id": 15,
  "name": "Lulita",
  "city": "Kunashak",
  "code": "ABP"
}, {
  "id": 16,
  "name": "Garald",
  "city": "Geidam",
  "code": "MAV"
}, {
  "id": 17,
  "name": "Cynthy",
  "city": "Rancho Nuevo",
  "code": "GKE"
}, {
  "id": 18,
  "name": "Hercule",
  "city": "Mapaniqui",
  "code": "AET"
}, {
  "id": 19,
  "name": "Ertha",
  "city": "Baiba",
  "code": "TVU"
}, {
  "id": 20,
  "name": "Bartie",
  "city": "Brest",
  "code": "BZL"
}, {
  "id": 21,
  "name": "Pate",
  "city": "Kelungkung",
  "code": "SNT"
}, {
  "id": 22,
  "name": "Audry",
  "city": "Inderka",
  "code": "WOA"
}, {
  "id": 23,
  "name": "Gaby",
  "city": "Jinsha",
  "code": "YYD"
}, {
  "id": 24,
  "name": "Gilles",
  "city": "Karlobag",
  "code": "RMF"
}, {
  "id": 25,
  "name": "Florentia",
  "city": "Pozhang",
  "code": "MQC"
}, {
  "id": 26,
  "name": "Steven",
  "city": "Surgut",
  "code": "TQP"
}, {
  "id": 27,
  "name": "Vincenty",
  "city": "Fontinha",
  "code": "YNO"
}, {
  "id": 28,
  "name": "Sammie",
  "city": "Pedaringan",
  "code": "VCP"
}, {
  "id": 29,
  "name": "Aurthur",
  "city": "Jianshan",
  "code": "PUS"
}, {
  "id": 30,
  "name": "Sarita",
  "city": "Zaragoza",
  "code": "YLR"
}, {
  "id": 31,
  "name": "Lorin",
  "city": "Beizheng",
  "code": "FAS"
}, {
  "id": 32,
  "name": "Jordan",
  "city": "Emmaboda",
  "code": "FWL"
}, {
  "id": 33,
  "name": "Anette",
  "city": "Lokavec",
  "code": "CKI"
}, {
  "id": 34,
  "name": "Emmie",
  "city": "Jinghai",
  "code": "PPW"
}, {
  "id": 35,
  "name": "Janis",
  "city": "Kragan",
  "code": "HUV"
}, {
  "id": 36,
  "name": "Rhona",
  "city": "Dongyong",
  "code": "0"
}, {
  "id": 37,
  "name": "Tracey",
  "city": "Long Layu",
  "code": "TOP"
}, {
  "id": 38,
  "name": "Suzette",
  "city": "Zinat",
  "code": "ZIC"
}, {
  "id": 39,
  "name": "Starlin",
  "city": "Kukichūō",
  "code": "NLK"
}, {
  "id": 40,
  "name": "Berk",
  "city": "Napuro",
  "code": "UBR"
}, {
  "id": 41,
  "name": "Carlie",
  "city": "Château-Richer",
  "code": "KBD"
}, {
  "id": 42,
  "name": "Annis",
  "city": "San Benito Abad",
  "code": "RDU"
}, {
  "id": 43,
  "name": "Orsa",
  "city": "Novhorod-Sivers’kyy",
  "code": "IAD"
}, {
  "id": 44,
  "name": "Catlee",
  "city": "Offa",
  "code": "BNC"
}, {
  "id": 45,
  "name": "Cazzie",
  "city": "Guiyang",
  "code": "OTJ"
}, {
  "id": 46,
  "name": "Ingrid",
  "city": "Le Hochet",
  "code": "ZAJ"
}, {
  "id": 47,
  "name": "Dinny",
  "city": "Dayrūţ",
  "code": "KME"
}, {
  "id": 48,
  "name": "Rayna",
  "city": "Ubinskoye",
  "code": "CMA"
}, {
  "id": 49,
  "name": "Ludovico",
  "city": "Isiolo",
  "code": "MVO"
}, {
  "id": 50,
  "name": "Orbadiah",
  "city": "Qian’an",
  "code": "NQY"
}]